name: Move new issues into Project Board

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
          project: issue-automation-test
          column: Todo
          